server:
  port: 9191
  tomcat:
    uri-encoding: UTF-8
spring:
  application:
    name: search
  data:
    elasticsearch:
      cluster-name: imood-elasticsearch

      cluster-nodes: 192.168.205.114:9300
  elasticsearch:
    rest:
      uris:
        - 192.168.205.114:9200




eureka:
  client:
    # 是否要把当前server注册
    register-with-eureka: true
    # 从注册中心查询检索服务实例，server的话没必要，直接false
    fetch-registry: true
    service-url:
      # 单实例配置自己的服务地址，高可用则配置其他服务的地址
      defaultZone: http://register-7070:7070/eureka/,http://register-7071:7071/eureka/,http://register-7072:7072/eureka/










