############################################################
#
# 文件微服务
# web访问端口号  约定：8004
#
############################################################
server:
  tomcat:
    uri-encoding: UTF-8
    max-swallow-size: -1  # tomcat默认大小2M，超过2M的文件不会被捕获，需要调整此处大小为100MB或者-1即可

############################################################
#
# 配置项目信息
#
############################################################
spring:
  profiles:
    active: dev   # yml中配置文件的环境配置，dev：开发环境，test：测试环境，prod：生产环境
  application:
    name: service-files
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  servlet:
    multipart:
      max-file-size: 512000   # 请求的文件大小限制为500kb
      max-request-size: 512000
  data:
    mongodb:
      uri: mongodb://root:root@192.168.205.118:27117
      database: imood-news
  elasticsearch:
    rest:
      uris:
        - 192.168.205.114:9200



############################################################
#
# fdfs 配置
#
############################################################
fdfs:
  connect-timeout: 30   # 连接的超时时间
  so-timeout: 30        # 读取的超时时间
  # TODO 修改生成环境的
  tracker-list: 192.168.205.116:22122   # tracker服务所在的ip地址和端口号

eureka:
  client:
    # 是否要把当前server注册
    register-with-eureka: true
    # 从注册中心查询检索服务实例，server的话没必要，直接false
    fetch-registry: true
    service-url:
      # 单实例配置自己的服务地址，高可用则配置其他服务的地址
      defaultZone: http://register-7070:7070/eureka/,http://register-7071:7071/eureka/,http://register-7072:7072/eureka/